### PR TITLE
Implement more mechanics (arbitrary colors, suns/stars, cancellation symbols)

### PR DESCRIPTION
**Pull request by cemulate**
Hey, really cool project!

Here's what's up in this pull request:

* You can now use all the colors from the game. I've changed the UX to accommodate this: left clicking on a cell cycles through types and right clicking on the background of a cell changes color (right clicking still toggles tetris pieces if you aim it properly) -- and yes tetris pieces need color too, there are puzzles that depend on a sun matching with a tetris piece of the same color.
* Implemented Suns/stars
* Implemented cancellation symbols (using my best interpretation of the mechanic). 

Here's an anchor tag for a puzzle using all the new mechanics. I've tested a bit but throwing it at some harder ones can't hurt.

    #eyJncmlkV2lkdGgiOjUsImdyaWRIZWlnaHQiOjUsImhvckVkZ2VzIjpbWzAsMCwwLDAsMF0sWzAsMCwwLDAsMF0sWzAsMCwwLDAsMF0sWzAsMCwwLDAsMF1dLCJ2ZXJFZGdlcyI6W1swLDAsMCwwXSxbMCwwLDAsMF0sWzAsMCwwLDBdLFswLDAsMCwwXSxbMCwwLDAsMF1dLCJub2RlVHlwZXMiOltbMCwwLDAsMCwxXSxbMCwwLDAsMCwwXSxbMCwwLDAsMCwwXSxbMCwwLDAsMCwwXSxbMywwLDAsMCwwXV0sImNlbGxUeXBlcyI6W1t7InR5cGUiOjUsImNvbG9yIjoxfSx7InR5cGUiOjAsImNvbG9yIjowfSx7InR5cGUiOjQsImNvbG9yIjowfSx7InR5cGUiOjQsImNvbG9yIjowfV0sW3sidHlwZSI6MSwiY29sb3IiOjF9LHsidHlwZSI6MCwiY29sb3IiOjB9LHsidHlwZSI6NCwiY29sb3IiOjB9LHsidHlwZSI6NCwiY29sb3IiOjB9XSxbeyJ0eXBlIjoxLCJjb2xvciI6MX0seyJ0eXBlIjowLCJjb2xvciI6MH0seyJ0eXBlIjowLCJjb2xvciI6MH0seyJ0eXBlIjowLCJjb2xvciI6MH1dLFt7InR5cGUiOjEsImNvbG9yIjowfSx7InR5cGUiOjAsImNvbG9yIjowfSx7InR5cGUiOjAsImNvbG9yIjowfSx7InR5cGUiOjAsImNvbG9yIjowfV1dLCJjZWxsVGV0cmlzTGF5b3V0cyI6W1tbWzEsMSwwLDBdLFsxLDEsMCwwXSxbMCwwLDAsMF0sWzAsMCwwLDBdXSxbWzEsMSwwLDBdLFsxLDEsMCwwXSxbMCwwLDAsMF0sWzAsMCwwLDBdXSxbWzEsMSwwLDBdLFsxLDEsMCwwXSxbMCwwLDAsMF0sWzAsMCwwLDBdXSxbWzEsMSwwLDBdLFsxLDEsMCwwXSxbMCwwLDAsMF0sWzAsMCwwLDBdXV0sW1tbMSwxLDAsMF0sWzEsMSwwLDBdLFswLDAsMCwwXSxbMCwwLDAsMF1dLFtbMSwxLDAsMF0sWzEsMSwwLDBdLFswLDAsMCwwXSxbMCwwLDAsMF1dLFtbMSwxLDAsMF0sWzEsMSwwLDBdLFswLDAsMCwwXSxbMCwwLDAsMF1dLFtbMSwxLDAsMF0sWzEsMSwwLDBdLFswLDAsMCwwXSxbMCwwLDAsMF1dXSxbW1sxLDEsMCwwXSxbMSwxLDAsMF0sWzAsMCwwLDBdLFswLDAsMCwwXV0sW1sxLDEsMCwwXSxbMSwxLDAsMF0sWzAsMCwwLDBdLFswLDAsMCwwXV0sW1sxLDEsMCwwXSxbMSwxLDAsMF0sWzAsMCwwLDBdLFswLDAsMCwwXV0sW1sxLDEsMCwwXSxbMSwxLDAsMF0sWzAsMCwwLDBdLFswLDAsMCwwXV1dLFtbWzEsMSwwLDBdLFsxLDEsMCwwXSxbMCwwLDAsMF0sWzAsMCwwLDBdXSxbWzEsMSwwLDBdLFsxLDEsMCwwXSxbMCwwLDAsMF0sWzAsMCwwLDBdXSxbWzEsMSwwLDBdLFsxLDEsMCwwXSxbMCwwLDAsMF0sWzAsMCwwLDBdXSxbWzEsMSwwLDBdLFsxLDEsMCwwXSxbMCwwLDAsMF0sWzAsMCwwLDBdXV1dLCJjZWxsVGV0cmlzQXJlYXMiOltbNCw0LDQsNF0sWzQsNCw0LDRdLFs0LDQsNCw0XSxbNCw0LDQsNF1dLCJjZWxsVGV0cmlzQm91bmRzIjpbW1swLDAsMSwxXSxbMCwwLDEsMV0sWzAsMCwxLDFdLFswLDAsMSwxXV0sW1swLDAsMSwxXSxbMCwwLDEsMV0sWzAsMCwxLDFdLFswLDAsMSwxXV0sW1swLDAsMSwxXSxbMCwwLDEsMV0sWzAsMCwxLDFdLFswLDAsMSwxXV0sW1swLDAsMSwxXSxbMCwwLDEsMV0sWzAsMCwxLDFdLFswLDAsMSwxXV1dfQ==

### CODE REVIEW

**Comment by cemulate** [comment]
Sorry, that was the wrong anchor tag.
This would be a better puzzle:

    #eyJncmlkV2lkdGgiOjUsImdyaWRIZWlnaHQiOjUsImhvckVkZ2VzIjpbWzAsMCwwLDAsMF0sWzAsMCwwLDAsMF0sWzAsMCwwLDAsMF0sWzAsMCwwLDAsMF1dLCJ2ZXJFZGdlcyI6W1swLDAsMCwwXSxbMCwwLDAsMF0sWzAsMCwwLDBdLFswLDAsMCwwXSxbMCwwLDAsMF1dLCJub2RlVHlwZXMiOltbMCwwLDAsMCwxXSxbMCwwLDAsMCwwXSxbMCwwLDAsMCwwXSxbMCwwLDAsMCwwXSxbMywwLDAsMCwwXV0sImNlbGxUeXBlcyI6W1t7InR5cGUiOjUsImNvbG9yIjoxfSx7InR5cGUiOjAsImNvbG9yIjowfSx7InR5cGUiOjQsImNvbG9yIjowfSx7InR5cGUiOjQsImNvbG9yIjowfV0sW3sidHlwZSI6MSwiY29sb3IiOjF9LHsidHlwZSI6MCwiY29sb3IiOjB9LHsidHlwZSI6NCwiY29sb3IiOjN9LHsidHlwZSI6NCwiY29sb3IiOjN9XSxbeyJ0eXBlIjoxLCJjb2xvciI6MX0seyJ0eXBlIjowLCJjb2xvciI6MH0seyJ0eXBlIjoxLCJjb2xvciI6MH0seyJ0eXBlIjo0LCJjb2xvciI6MH1dLFt7InR5cGUiOjEsImNvbG9yIjo0fSx7InR5cGUiOjAsImNvbG9yIjowfSx7InR5cGUiOjIsImNvbG9yIjozfSx7InR5cGUiOjQsImNvbG9yIjozfV1dLCJjZWxsVGV0cmlzTGF5b3V0cyI6W1tbWzEsMSwwLDBdLFsxLDEsMCwwXSxbMCwwLDAsMF0sWzAsMCwwLDBdXSxbWzEsMSwwLDBdLFsxLDEsMCwwXSxbMCwwLDAsMF0sWzAsMCwwLDBdXSxbWzEsMSwwLDBdLFsxLDEsMCwwXSxbMCwwLDAsMF0sWzAsMCwwLDBdXSxbWzEsMSwwLDBdLFsxLDEsMCwwXSxbMCwwLDAsMF0sWzAsMCwwLDBdXV0sW1tbMSwxLDAsMF0sWzEsMSwwLDBdLFswLDAsMCwwXSxbMCwwLDAsMF1dLFtbMSwxLDAsMF0sWzEsMSwwLDBdLFswLDAsMCwwXSxbMCwwLDAsMF1dLFtbMSwxLDAsMF0sWzEsMSwwLDBdLFswLDAsMCwwXSxbMCwwLDAsMF1dLFtbMSwxLDAsMF0sWzEsMSwwLDBdLFswLDAsMCwwXSxbMCwwLDAsMF1dXSxbW1sxLDEsMCwwXSxbMSwxLDAsMF0sWzAsMCwwLDBdLFswLDAsMCwwXV0sW1sxLDEsMCwwXSxbMSwxLDAsMF0sWzAsMCwwLDBdLFswLDAsMCwwXV0sW1sxLDEsMCwwXSxbMSwxLDAsMF0sWzAsMCwwLDBdLFswLDAsMCwwXV0sW1sxLDEsMCwwXSxbMSwxLDAsMF0sWzAsMCwwLDBdLFswLDAsMCwwXV1dLFtbWzEsMSwwLDBdLFsxLDEsMCwwXSxbMCwwLDAsMF0sWzAsMCwwLDBdXSxbWzEsMSwwLDBdLFsxLDEsMCwwXSxbMCwwLDAsMF0sWzAsMCwwLDBdXSxbWzAsMCwwLDBdLFswLDEsMSwwXSxbMCwwLDAsMF0sWzAsMCwwLDBdXSxbWzEsMSwwLDBdLFsxLDEsMCwwXSxbMCwwLDAsMF0sWzAsMCwwLDBdXV1dLCJjZWxsVGV0cmlzQXJlYXMiOltbNCw0LDQsNF0sWzQsNCw0LDRdLFs0LDQsNCw0XSxbNCw0LDIsNF1dLCJjZWxsVGV0cmlzQm91bmRzIjpbW1swLDAsMSwxXSxbMCwwLDEsMV0sWzAsMCwxLDFdLFswLDAsMSwxXV0sW1swLDAsMSwxXSxbMCwwLDEsMV0sWzAsMCwxLDFdLFswLDAsMSwxXV0sW1swLDAsMSwxXSxbMCwwLDEsMV0sWzAsMCwxLDFdLFswLDAsMSwxXV0sW1swLDAsMSwxXSxbMCwwLDEsMV0sWzEsMSwxLDJdLFswLDAsMSwxXV1dfQ==

Here's a picture of the result:

image

**Comment by cemulate** [comment]
Also just a heads up: 

Since this is just a static site, you can serve it right from Github Pages, just by making a `gh-pages` branch. Github will automatically serve the directory pointed at by `gh-pages` if you go to `username.github.io/repo-name`.

I'm doing it for my fork currently: [https://cemulate.github.io/TheWitnessSolver/](https://cemulate.github.io/TheWitnessSolver/)

**Comment by Overv** [comment]
Great work! Especially impressive considering my code quality for this particular project :P

I will also look into the Github Pages thing.

**Edit:** I've set up the branch and added a link to the README.

**Comment by cemulate** [comment]
> Especially impressive considering my code quality for this particular project

Heh, I wasn't going to bring it up but I completely understand. I was thinking about doing my own with a proper ES6 toolchain when I found yours. You'd already done the UI, which was the part I had *no desire* to do, so I figured I'd be happier forking yours. It's not even *too* bad for a smallish project like this.

**Pull request merged**
